---
# tasks file for loadbalancer
- package:
        name: "{{package_name}}"
        state: present
- template: 
        dest: "/etc/haproxy/haproxy.cfg"
        src: "haproxy.cfg"
  notify: "loadbalancer"

